# Generated by Django 4.1.3 on 2022-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('lat', 'lon')},
        ),
    ]
