# Generated by Django 4.1.3 on 2022-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lon',
            field=models.FloatField(verbose_name='долгота'),
        ),
    ]
