# Generated by Django 4.1.3 on 2022-11-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_lat_alter_city_lon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
