# Generated by Django 4.1.3 on 2022-11-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_city_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.SmallIntegerField(verbose_name='температура')),
                ('clouds', models.SmallIntegerField(blank=True, null=True, verbose_name='облачность')),
                ('wind_speed', models.SmallIntegerField(blank=True, null=True, verbose_name='скорость ветра')),
                ('rain', models.SmallIntegerField(blank=True, null=True, verbose_name='количество осадков (дождя)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_now', to='cities.city', verbose_name='город')),
            ],
        ),
    ]
