# Generated by Django 4.1.3 on 2022-11-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='clouds',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='rain',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
    ]
