# Generated by Django 4.1.3 on 2022-11-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_weather_clouds_remove_weather_rain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
    ]
